[package]
name = "plotters_backend_iced_app"
version = "0.1.0"
authors = ["hibi221b"]
edition = "2018"

[dependencies.iced]
version = "0.2.0"
features = [
    "canvas"
]

[dependencies]
plotters = "0.3.0"
plotters-backend = "0.3.0"